/** AUTHENTICATION  */
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGOUT = "LOGOUT"


/** POST */

//FETCH OR GET DATA
export const FETCH_POST_LOADING = "FETCH_POST_LOADING"
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"
export const FETCH_POST_FAILED = "FETCH_POST_FAILED"
export const FETCH_TAGS = "FETCH_TAGS"
export const FETCH_POST_BY_TITLE = "FETCH_POST_BY_TITLE"
export const GET_POST_BY_TAG = "GET_POST_BY_TAG"

//FILTER OR SORTS POST
export const FILTER_POST_BY_TITLE = "FILTER_POST_BY_TITLE"
export const SORT_POST_BY_DATE = "SORT_POST_BY_DATE"

//DELETE
export const DELETE_POST_BY_ID = "DELETE_POST_BY_ID"


/** PROJECT */

//FETCH
export const FETCH_PROJECT_LOADING = "FETCH_PROJECT_LOADING"
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS"
export const FETCH_PROJECT_FAILED = "FETCH_PROJECT_FAILED"
export const FETCH_PROJECT_BY_NAME = "FETCH_PROJECT_BY_NAME"
export const FETCH_PROJECTS_BY_TAGNAME = "FETCH_PROJECTS_BY_TAGNAME"
//DELETE 
export const DELETE_PROJECT_BY_ID = "DELETE_PROJECT_BY_ID"
//FILTER OR SORT
export const FILTER_PROJECT_BY_NAME = "FILTER_PROJECT_BY_NAME"
export const FILTER_PROJECT_BY_IN_CITY="FILTER_PROJECT_BY_IN_CITY"
export const FILTER_PROJECT_BY_TAG_DISTRICT="FILTER_PROJECT_BY_TAG_DISTRICT"

/** PRODUCTS */
    //FETCH
export const FETCH_ROOMS ="FETCH_ROOMS"
export const FETCH_PRODUCTS="FETCH_PRODUCTS"
export const FETCH_PRODUCT_BY_NAME="FETCH_PRODUCT_BY_NAME"

 //DELETE
 export const DELETE_PRODUCT_BY_ID="DELETE_PRODUCT_BY_ID"

